### PR TITLE
Support for building MicrosoftEdge Linux images (related to #302)

### PR DESCRIPTION
**Pull request by vania-pooh**
@ruescar JFYI

### CODE REVIEW

**Comment by vania-pooh** [comment]
@amisuna this is development version, not yet fully tested. Channel was added for future beta version that should be published soon.

**Comment by amisuna** [comment]
@vania-pooh Thank you for your response.
BTW:
I already created container for edge and do some smoke testing - 
working well for Selenium 3 and Selenium 4 alpha 6

**Comment by vania-pooh** [comment]
@amisuna already built here: https://aerokube.com/images/latest/#_microsoft_edge

**Comment by amisuna** [comment]
@vania-pooh yes, thank you.

**Pull request merged**
