### PR TITLE
Fixed YandexDriver version selection + refactoring

### PR DESCRIPTION
**Pull request by ruescar**
- This implementation is still the only valid one, since https://github.com/yandex/YandexDriver/issues/3 is still open
- Regression tested all browsers for all channels with apt method

### CODE REVIEW

**Comment by vania-pooh** [comment]
@ruescar too many changes, could you describe the main idea?

**Comment by ruescar** [comment]
> @ruescar too many changes, could you describe the main idea?

@vania-pooh This PR is just about retrieving the correct latest YandexDriver Linux version looping through all the releases until the first Linux version is found. This is needed since YandexDriver releases don't include all binaries for all platforms. This implementation is the same one I did for the bash version. I also did some refactoring because I ended up with a lot of duplicate code for the Github Api Get requests.
If you think these are too many changes and expect YandexDriver project to fix https://github.com/yandex/YandexDriver/issues/3 soon so that we can use the current code, maybe we can consider this other PR #284 instead, which contains just the change needed without the refactoring. And then it would be very easy to revert this change.

**Comment by ruescar** [comment]
@vania-pooh Before I rebase on top latest changes from master, please let me know if you are more keen for this PR or #284

**Comment by vania-pooh** [comment]
@ruescar thank you for contribution!

**Pull request merged**
